dist: bionic
language: cpp

compiler:
  - clang
  - gcc
os:
  - linux

script:
  - mkdir build && cd build && cmake .. && cd ..
  - cmake --build build --target all
  - cmake --build build --target test
  - cmake --build build --target run_all_java_client_test_for_cpp_server


