version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: "Install Packages"
          command: apt-get update && apt-get install -y gcc clang cmake
      - run:
          name: "Generate CMake project"
          command: mkdir build && cd build && cmake .. && cd ..
      - run:
          name: "Build all"
          command: cmake --build build --target all
      - run:
          name: "Test"
          command: cmake --build build --target test          
      - run:
          name: "Java Integration Tests"
          command: cmake --build build --target run_all_java_client_test_for_cpp_server     
workflows:
  build-workflow:
    jobs:
      - build
